#
#	'Perception.Library' Build Scripting
#
IDLTOOL	=	SDK:C/idltool
MKDIR	=	C:Makedir
RM		=	C:Delete ALL FORCE QUIET

automagic:
	${IDLTOOL} -p -n -i perception.xml

clean:
	@ ${RM} Include/proto Include/inline Include/inline4 Include/interfaces
