#
#	'Perception.Library' Build Scripting
#
MAKE		=	make
AREXX		=	REXX:RX
PYTHON		=	Python:Python
MKDIR		=	Makedir
RM 			=	Delete ALL QUIET

main:
	XadUnFile	/Resources/Unicode/Unihan.zip /Catalogs/ OW
#	@ $(AREXX)	CodePointParser.rexx
#	@ Echo	$(PYTHON)	CodePointParser.py
#	@ $(AREXX)	CodePointCompilation.rexx

clean:
	@ Echo >dummy.txt " "
	@ Echo >dummy.cd " "
	@ Echo >dummy.ct " "
	@ $(RM) #?.txt #?.cd #?.ct ALL FORCE QUIET

#
