#
#	'Perception.Library' Build Scripting
#
MAKE	=	make

main:
	@ ${MAKE} -C Chinese  -f GNUmakefile
	@ ${MAKE} -C Japanese -f GNUmakefile
	@ ${MAKE} -C Korean   -f GNUmakefile

clean:
	@ ${MAKE} -C Chinese  -f GNUmakefile clean
	@ ${MAKE} -C Japanese -f GNUmakefile clean
	@ ${MAKE} -C Korean   -f GNUmakefile clean

install:
	@ ${MAKE} -C Chinese  -f GNUmakefile install
	@ ${MAKE} -C Japanese -f GNUmakefile install
	@ ${MAKE} -C Korean   -f GNUmakefile install
