#
#	'Perception.Library' Build Scripting
#
MAKE	=	make

main:
	@ ${MAKE} -C iso-2022-cn     -f GNUmakefile
	@ ${MAKE} -C iso-2022-jp     -f GNUmakefile
	@ ${MAKE} -C shift_jis       -f GNUmakefile
	@ ${MAKE} -C iso-2022-kr     -f GNUmakefile

clean:
	@ ${MAKE} -C iso-2022-cn     -f GNUmakefile clean
	@ ${MAKE} -C iso-2022-jp     -f GNUmakefile clean
	@ ${MAKE} -C shift_jis       -f GNUmakefile clean
	@ ${MAKE} -C iso-2022-kr     -f GNUmakefile clean

install:
	@ ${MAKE} -C iso-2022-cn     -f GNUmakefile install
	@ ${MAKE} -C iso-2022-jp     -f GNUmakefile install
	@ ${MAKE} -C shift_jis       -f GNUmakefile install
	@ ${MAKE} -C iso-2022-kr     -f GNUmakefile install
